// array of some common keywrods used to fetch images from unsplash api
// we use this to show suggestions
const searchKeywords = [
  "Majestic Snowy Peaks",
  "Rugged Cliff Views",
  "Pine-covered Slopes",
  "Adventure in Heights",
  "Rocky Stream Flow",
  "Golden Sunrise Peaks",
  "Cozy Mountain Cabins",
  "Misty Valley Serenity",
  "Reflective Alpine Lakes",
  "Goats on Slopes",
  "Ancient Peak Legends",
  "Starry Night Skies",
  "Silent Mountain Symphony",
  "Hidden Cave Treasures",
  "Wildflower Meadow Bliss",
  "Waterfall Cascades Down",
  "The sun sets over the horizon, painting the sky in warm hues.",
  "A bustling cityscape with skyscrapers reaching for the clouds.",
  "Dew glistens on blades of grass in the morning light.",
  "A close-up of a delicate butterfly resting on a flower.",
  "Abstract patterns of light and shadow dance on the walls.",
  "The intricate details of Gothic architecture leave one in awe.",
  "Exploring ancient ruins that hold secrets of the past.",
  "A steaming cup of coffee on a rustic wooden table.",
  "A chef meticulously plating a gourmet dish.",
  "A team of professionals brainstorming ideas in a boardroom.",
  "A mother and child share a tender moment in the park.",
  "Inspirational quotes framed against breathtaking landscapes.",
  "Athletes giving their all in a fiercely competitive match.",
  "Tools of an artist spread out on a cluttered workbench.",
  "A minimalist living space with clean lines and neutral tones.",
  "Music fills the air as concert-goers lose themselves in the rhythm.",
  "A drone captures a bird's eye view of a vibrant city.",
  "A serene yoga studio with soft lighting and calming decor.",
  "Fresh fruits and vegetables arranged in a farmer's market.",
  "The laughter of children echoing through a playground.",
  "Vintage cars gleaming under the sun at a car show.",
  "A couple dances under the stars on a warm summer night.",
  "Autumn leaves carpet the ground in a riot of colors.",
  "A snow-covered landscape, a winter wonderland.",
  "A surfer catches a wave as the sun sets on the horizon.",
  "Children's faces lit up with wonder at a carnival.",
  "Intricate lace patterns on a wedding dress.",
  "Fireworks illuminating the night sky in a burst of color.",
  "A cozy reading nook by a window with a view.",
  "Snowflakes gently falling, blanketing the world in white.",
  "Hands reaching out to touch a field of wheat.",
  "A cat curled up by a fireplace, basking in the warmth.",
  "Raindrops glistening on a spider's web.",
  "A boat peacefully gliding on a tranquil lake.",
  "Rows of colorful houses along a canal.",
  "A lone tree standing tall in a golden field.",
  "A vintage typewriter, keys poised for creativity.",
  "A reflection of city lights on a rainy street.",
  "Sand dunes stretching out into the desert.",
  "Waves crashing against rugged coastal cliffs.",
  "Street art bringing vibrancy to a city alleyway.",
  "A lone hiker on a winding mountain trail.",
  "A tranquil garden with a stone pathway.",
  "The silhouette of a lone wolf against the moon.",
  "Golden hour casting a warm glow over the landscape.",
  "A field of lavender in full bloom.",
  "A close-up of a musician's hands on a guitar.",
  "Patterns in the sand left by the tide.",
  "Fairy lights twinkling in an outdoor garden.",
  "Abstract swirls of paint on a canvas.",
  "Waves gently lapping at a sandy shore.",
  "Nature",
  "Cityscape",
  "Landscape",
  "Portrait",
  "Abstract",
  "Architecture",
  "Travel",
  "Food",
  "Technology",
  "Business",
  "People",
  "Animals",
  "Fashion",
  "Art",
  "Sports",
  "Fitness",
  "Music",
  "Health",
  "Education",
  "Vintage",
  "Cars",
  "Flowers",
  "Sunset",
  "Beach",
  "Mountains",
  "Sky",
  "Water",
  "Urban",
  "Wildlife",
  "Pets",
  "Home",
  "Family",
  "Friends",
  "Love",
  "Adventure",
  "Celebration",
  "Holiday",
  "Halloween",
  "Christmas",
  "New Year",
  "Easter",
  "Summer",
  "Winter",
  "Autumn",
  "Spring",
  "Rain",
  "Snow",
  "Sunrise",
  "Sunset",
  "Stars",
];
export default searchKeywords;
